#See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow for help
name: ContinuousBuild
#Set when this build is activated. This can be once x time period, or on push/commit of certain branches
on:
  schedule:
    #uses the POSIX cron syntax. The below runs every 10 minutes
    - cron: '*/5 * * * *'
  push:
    branches: 
      - master
jobs:
  job1:
    name: BuildRoslyn
    runs-on: windows-latest #Specify the OS to execute on
    env:
      RoslynDir: ./Roslyn
      XSharpDir: ./XSharp
    
    steps:
      - name: RestoreRoslyn
        run: Restore.cmd
        working-directory: ${{env.RoslynDir}} #we do this in the roslyn subdirectory
