#See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow for help
name: ContinuousBuild
#Set when this build is activated. This can be once x time period, or on push/commit of certain branches
on:
  schedule:
    #uses the POSIX cron syntax. The below runs every houe
    - cron: '0 * * * *'
  push:
    branches: 
      - master
jobs:
  job1:
    name: BuildRoslyn
    runs-on: windows-latest #Specify the OS to execute on
    env:
      RoslynDir: ./Roslyn
      XSharpDir: ./XSharp
    
    steps:
      - uses: actions/checkout@master #Clone the repository code at master
      - name: Setup MSBuild Path
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: RestoreRoslyn
        run: ./Restore.cmd 
        working-directory: ${{env.RoslynDir}} #we do this in the roslyn subdirectory
